main: me.prisonranksx.PrisonRanksX
version: "3.0"
name: PrisonRanksX
author: "TheGaming999/Sandwicha"
depend: [Vault]
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, HolographicDisplays, ActionUtil, PermissionsEX, GroupManager, LuckPerms, DecentHolograms]
api-version: 1.13